### ISSUE TITLE
Missing requirement: direnv

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/kuebiko#15]
When running `make_install` I got 

```
/bin/bash: direnv: command not found
make: *** [install] Error 127
```

I fixed this with `brew install direnv`. Perhaps worth adding to the requirements here or in the cookiecutter installation guide?

**Comment by bishax** [comment]
It lists `direnv` in the README.

The cookiecutter installation guide (http://nestauk.github.io/ds-cookiecutter/quickstart) will mention `direnv` when https://github.com/nestauk/ds-cookiecutter/pull/92 (the setup overhaul which `kuebiko` is based on) is merged.

**Comment by Juan-Mateos** [comment]
Sorry! I skim-read that part because I thought I had already covered this when I installed the dependencies for the `ds-cookiecutter` first time around.
